name: Index repo

on:
  repository_dispatch:
    types:
    - chart-available

jobs:
  index:
    name: Index Chart Repo
    runs-on: ubuntu-latest
    env:
      RELEASE_PAYLOAD: ${{ toJson(github.event) }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_GITHUB }}

    - name: download chart & index repo
      run: |
        curl -L -o ${{ github.event.client_payload.name }} \
          -H "Authorization: token ${{ secrets.PAT_GITHUB }}" \
          -H 'Accept: application/octet-stream' \
          ${{ github.event.client_payload.uri }}
        
        helm show chart ${{ github.event.client_payload.name }} | tee chart-info.yaml
        chartName=$(cat chart-info.yaml | grep -Po "^name:\s?(.*)$" | cut -d' ' -f2 | tr -d '\r\n')
        helmVersion=$(cat chart-info.yaml | grep -Po "^version:\s?(.*)$" | cut -d' ' -f2 | tr -d '\r\n')

        rm -f chart-info.yaml

        helm repo index . --url https://alexismtr.github.io/poseidon-helm-chart/ --merge index.yaml
        
        git add .
        git commit -a -m "${chartName}: index version ${helmVersion}"
        git push